from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('slice.views',
    url(r'^list/(?P<proj_id>\d+)/(?P<stype>\d+)/$', "list", name='slice_list'),
    url(r'^create/(?P<proj_id>\d+)/$', "create", name='create_slice'),
    url(r'^create_first/(?P<proj_id>\d+)/$', "create_first", name='create_first_slice'),
    url(r'^delete/(?P<slice_id>\d+)/$', "delete", name='delete_slice'),
    url(r'^detail/(?P<slice_id>\d+)/$', "detail", name='slice_detail'),
    url(r'^start_or_stop/(?P<slice_id>\d+)/(?P<flag>\d+)/$', "start_or_stop", name='start_or_stop'),
    url(r'^topology/(?P<slice_id>\d+)/$', "topology", name='slice_topology'),
    url(r'^edit_description/(?P<slice_id>\d+)/$', "edit_description", name='edit_slice_description'),
    url(r'^edit_controller/(?P<slice_id>\d+)/$', "create_or_edit_controller", name='edit_slice_controller'),
    url(r'^check_slice_name/$', "check_slice_name", name='check_slice_name'),
    url(r'^create_nw/(?P<owner>\w+)/(?P<nw_num>\w+)/$', "create_nw", name='create_nw'),
    url(r'^delete_nw/(?P<owner>\w+)/$', "delete_nw", name='delete_nw'),
    url(r'^get_show_slices/$', "get_show_slices", name='get_show_slices'),
    url(r'^topology_test/(?P<slice_id>\d+)/$', "topology_test", name='topology_test'),
    url(r'^topology_d3/$', "topology_d3", name='topology_d3'),
    url(r'^update_links_bandwidths/(?P<slice_id>\d+)/$', "update_links_bandwidths", name='update_links_bandwidths'),
    url(r'^get_count_show/$', "get_count_show", name='get_count_show'),
    url(r'^countiframe/$', "countiframe", name='countiframe'),
    url(r'^dhcp_switch/(?P<slice_id>\d+)/(?P<flag>[0-1])/$', "dhcp_switch", name='dhcp_switch'),
    url(r'^get_slice_state/(?P<slice_id>\d+)/$', "get_slice_state", name='get_slice_state'),
)
